<a href="https://colab.research.google.com/github/amann-03/PyTorch_Implementations/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


Introduction to Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # no. of pairs of closing square brackets

1

In [ ]:
vector.shape

torch.Size([2])

Scalar - 0 - lower(a)
Vector - 1 - lower(y)
Matrix - 2 - Upper(Q)
Tensor - n - Upper(X)
Here, numbers are the dimensions

In [ ]:
# Matrix
Matrix = torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim # 2 square brackets

2

In [ ]:
Matrix[1]

tensor([ 9, 10])

In [ ]:
Matrix[0][1]

tensor(8)

In [ ]:
Matrix.shape # basically a 2*2 matrix here

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim # dim is 0-indexed

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random Tensors are important becuase the way neural networks learn is that they start with tensors full iof random numbers and then adjust those random numbers to better represent the data.

In [ ]:
random_tensor = torch.rand(3,4) # we specified the size that is shape
random_tensor

tensor([[0.2988, 0.0365, 0.3157, 0.7265],
        [0.8630, 0.3908, 0.7570, 0.8156],
        [0.7160, 0.9990, 0.7969, 0.7800]])

In [ ]:
random_tensor.ndim

2

In [ ]:
rand_tensor = torch.rand(1,5,5)
rand_tensor

tensor([[[0.3948, 0.5550, 0.2665, 0.3256, 0.4947],
         [0.0307, 0.3060, 0.7788, 0.8254, 0.7337],
         [0.1214, 0.2776, 0.4495, 0.1491, 0.9837],
         [0.3425, 0.3758, 0.0104, 0.3020, 0.8337],
         [0.5469, 0.9163, 0.8651, 0.0262, 0.4038]]])

In [ ]:
rand_tensor.ndim

3

In [ ]:
# Create random tensor with similar dhape to an image tensor
rand_img_size_tensor = torch.rand(size=(224,224,3)) #(height,width,color-channels(R,G,B))
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

ZEROS AND ONES

In [ ]:
# create tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype # default is float32

torch.float32

Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=1,end=11,step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros # gives same shape but with different values

tensor([0, 0, 0, 0, 0])

TENSOR DATATYPES

In [ ]:
# Float 32 tensor if dtype is NONE
default_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
default_tensor
# device tells -> what device is my tensor on (default = cpu)
# requires_grad -> whether or not to track the gradients of my tensor

tensor([3., 6., 9.])

In [ ]:
default_tensor.dtype

torch.float32

Single Precision = Float32
Half Precision = Float16
Theu represent in how much detail then number is stored in memory

In [ ]:
# can convert tensor from one datatype to another datatype
float_16_tensor = default_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

Tensor Dataypes are one of the 3 big reasons that leads to errors in pytorch and deep learning.
1. Tensors not in right datatype - tensor.dtype
2. Tensors not in right shape - tensor.shape
3. Tensors not on right device(like cpu, gpu, cuda) - tensor.device

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_16_tensor * int_32_tensor # not works with long - this is a type of caveat

tensor([ 9., 36., 81.], dtype=torch.float16)

 ### MAnipulating Tensors

Operations Include:
Addition
Subtraction
Multiplication
Division
Matrix Multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
tensor = torch.div(tensor,2)
# similarly, there are functions like add, mul, sub..

In [ ]:
tensor

tensor([0.5000, 1.0000, 1.5000])

### Matrix MUltiplication

2 main ways of performing multiliplication in neuarl networks and deep learning

1. Element wise
2. Matrix Multiplication

In [ ]:
# element wise
tensor = torch.mul(tensor,2)
tensor*tensor

tensor([1., 4., 9.])

In [ ]:
tensor.dtype

torch.float32

In [ ]:
# Matrix multiplication - torch.matmul()
torch.matmul(tensor,tensor)
# @ symbol is also used for matrix multiplication


tensor(14)

For matrix multiplication, inner dimensions must match
3*2 and 2*3 will work but 3*2 and 3*2 won't work
The resulting matrix has outer dimensions of matrix.
1. One of the most common errors in deep learning is shape error

1. To fix out tensor shape issues , we can manipulate the shape of our tensor using a transpose.
2. It switches the axes or dimensions of a vector

In [ ]:
tA = torch.tensor([[1,2],[3,4],[5,6]])
tB = torch.tensor([[7,8],[9,10],[11,12]])

In [ ]:
# torch.matmul(tA,tB) -> will give error as inner dimesnions are not same
tA.T,tA.shape
# got the transpose of matrix A

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([3, 2]))

In [ ]:
torch.matmul(tA.T,tB)

tensor([[ 89,  98],
        [116, 128]])

In [ ]:
torch.matmul(tA,tB.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding min, max,mean,sum,etc (Tensor Aggregation)

In [ ]:
x = torch.arange(0,100,10)
x
x.dtype

torch.int64

In [ ]:
torch.min(x), x.min() # get min

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max() # get max

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
# for mean to work, dtype should be either floating point or complex types, Integers won't work.

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### finding positional min and max

In [ ]:
# getting the index at which maximuma nd minimum occurs in the tensor
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping, Viewing and Stacking
1. Reshaping - reshapes an input tensor to a defined shape
2. View - Return a view of an input tensor of certain shape but keep the same memory as the original vector(a different perspective of viewing the tensor)
3. Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)

In [ ]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshape = x.reshape(9,1)
x_reshape, x_reshape.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1,9)
z, z.shape
# it is quite similar to reshape but shares the same memory with x

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# changing z changes the x
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# stack tensors on top
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked
# dim = 0 stacks tensors vertically

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# stack tensors horizontally
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked
# dim=1 stacks tensors horizontally

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

### Squuezing, Unsqueezing and permutting the tensors

In [ ]:
# torch.squueze() -> removes all single dimensions from a target tensor
x_reshape.shape, x_reshape.squeeze().shape

(torch.Size([1, 9]), torch.Size([9]))

In [ ]:
x_reshape = x_reshape.squeeze()# removed the outer square bracket which was of dimension 1
x_reshape

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# torch.unsqueeze() -> adds a single dimension to a target tensor at a specific dim(dimension)
# dim specifies where that single dimesion going to be added
x_unsqueeze = x_reshape.unsqueeze(dim=0)
x_unsqueeze

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_unsqueeze = x_reshape.unsqueeze(dim=1)
x_unsqueeze

tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
# torch.permute() -> rearranges the dimensions of a target tensor in a specified oerder
x_original = torch.rand(size=(224,224,3)) #(height,width,color_channels)

# permute the org_tensor to rearrange the axis(or dim) order
x_permute = x_original.permute(2,0,1) # shifts axis 0->1,1->2,2->1

In [ ]:
x_permute.shape #shares the same space in memory with x_original as it is a kind of view only

torch.Size([3, 224, 224])

### Selecting data from tensors(Indexing)

In [ ]:
x = torch.arange(1,10).reshape(1,3,3) # as total 9 elements are present
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# let's index our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
#let's index on most inner bracket(last dimension)
x[0][0][2]

tensor(3)

In [ ]:
# we can use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]
# get all valies of the 0 dimension but only 1 index value of 1st and 2nd dimension

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

### Pytorch and Numpy
1. Numpy is a popular scientific python numerical computing library
2. And bcoz. of this, Pytorch has functionality to interact with it
3. Data in Numpy, want in PyTorch Tensor -> torch.from_numpy(ndarray)
4. Pytorch tensor->Numpy : torch.tensor.numpy()

In [ ]:
array = np.arange(1.0,8.0) # default dtype id float64
tensor = torch.from_numpy(array)
array, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float64)

In [ ]:
# since tensors dtype deault is float32 but it reflects the dtype of numpy while conversion
# can explicitly convert the dtype
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [ ]:
# changing the value of array won't reflect the change in numpy
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype # reflects the original dtype of tensor

dtype('float32')

In [ ]:
# changing the tensor won't reflect the change in numpy
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility(taking the random out of random)
1. In short how neural network learns:
start with random numbers -> update them -> try to fit to the data -> update them -> again -> again -> again....

2. To reduce the randomness in neural networks and Pytorch, comes the concept of **random seed**. It flavours the randomness.

In [ ]:
rand_tA = torch.rand(3,4)
rand_tB = torch.rand(3,4)
print(rand_tA == rand_tB)
rand_tA, rand_tB

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


(tensor([[0.0060, 0.8775, 0.3177, 0.3162],
         [0.4270, 0.8080, 0.1021, 0.4408],
         [0.5747, 0.5566, 0.0356, 0.1234]]),
 tensor([[0.4631, 0.3578, 0.7556, 0.2457],
         [0.1364, 0.6389, 0.9160, 0.3343],
         [0.7291, 0.4616, 0.1087, 0.0147]]))

In [ ]:
# Let's make random but reproducable tensors

RANDOM_SEED = 42 # flavor of randomness
# 42 is universally chosen
torch.manual_seed(RANDOM_SEED)

rand_tC = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rand_tD = torch.rand(3,4)
print(rand_tC == rand_tD)
rand_tC,rand_tD

# Remember -> for flavoured randomness, you should call everytime torch.manual_seed()
# before using torch.rand

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

### Running Tensors and Pytorch objects on the GPU's(and making faster computations)

1. GPUs = faster computation on numbers, thanks to CUDA + NVIDIAhardware + PyTorch working behind the scenes.

For now, use google collab for free GPU.

In [ ]:
torch.cuda.is_available()

True

In [ ]:
 # setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
# putting tensors and models on GPU
# as it results in faster computations

tensor = torch.tensor([1,2,3])
print(tensor,tensor.device) # bydefault to cpu

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu
# 0 is the index of which gpu , currently we have only one gpu

tensor([1, 2, 3], device='cuda:0')

### Moving Tensors back to CPU
**If tensor is on gpu, can't transform to Numpy**

In [ ]:
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy() # first put back to cpu
tensor_back_to_cpu

array([1, 2, 3])

In [ ]:
# can also set amnual seed on cuda
# by torch.cuda.manual_seed(7)